# config.yaml
#Below the input and output directories are specified
input_dir: /Users/johnoconnor/MetaEuk_Remote/input
output_dir: /Users/johnoconnor/MetaEuk_Remote/output
#We include a metadata file for sample identification
METADATA: /Users/johnoconnor/MetaEuk_Remote/metadata/metadata.xlsx
#We indicate where the databases are stored 
database_dir: /Users/johnoconnor/MetaEuk_Remote/ref_databases
